### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by fixyabrokestuff** [AccelerateNetworks/PagingServer#14]
I've tried installing the project with the readme directions but I'm getting nowhere.  The installation will register the sip client and attempt to take a call but no answer, no audio and lots of errors.  I've never used jack before and it's not clear to me that it's necessary for the app to work although it appears to be.  I'm really looking for guidance on configuring the audio output part of things.

So far my efforts have been to configure the project on a Raspberry Pi,  a VM running Debian 8.5.0 and Ubuntu 16.04.  No joy and very little sleep.

Here is a sample of the debug output when the system connects and a call is recieved

[Paging Debug Output.txt](https://github.com/AccelerateNetworks/PagingServer/files/467473/Paging.Debug.Output.txt)
![pulse audio volume control playback](https://cloud.githubusercontent.com/assets/22148454/18438726/86ad2700-78d0-11e6-8550-4064126247e3.png)
![pulse audio volume control recording](https://cloud.githubusercontent.com/assets/22148454/18438730/8cd8bb94-78d0-11e6-8b5d-f956542ba81c.png)

**Comment by mk-fg** [comment]
Hey,

From "Paging Debug Output.txt" and images above:
- Only paging.py error there (one with traceback) seem to be due to missing klaxon path, i.e. you have non-existing or otherwise inaccessible path configured as klaxon, though that error message can definitely be nicer.
- Not sure which version of the script you're using - e.g. `File "/usr/lib/python2.7/dist-packages/paging.py", line 702, in wav_length` clearly points to different line when it is in the current code. Did you install it from .deb? If so, which package version? Maybe it's missing for some arch in the repo (should not, but it seem more likely than unintentionally non-latest from git).
- Why do you even have JACK installed and mention it? It shouldn't be used by current script in any way at all, README barely mentions it as one of possible portaudio outputs, but that should be it.
- Looking for actual sound issues, see this in the log:

```
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

That suggests following to me:
- pjsip/pjsua is built with ALSA and JACK support.
- pjsua tries to use ALSA first, which it should to get sound to pulse (see README for more details), but it fails due to what looks like asound.conf issue (can you get sound from e.g. aplay as the same uid?).
- Then pjsua goes ahead and uses JACK (auto-started server) for output. If that wouldn't have worked, it'd have failed to start, but it works.

Where sound is routed in JACK I don't know, but from your other comments, that doesn't seem to be intentional.

So the gist is that either configured or default alsa output doesn't work.
I'd suggest following:
- Remove or disable JACK, forget it exists for the scope of this project, has nothing to do with it (unless, of course, you want to use it somehow).
- Check `aplay -L` for list of available alsa output devices/modules (as configured in alsa)
- Find output that leads to pulse (or something leading to it) there (can be "default" or "pulse"), test it via e.g. `aplay -D pulse mysound.wav` from the same uid as you'd run paging.py (e.g. `machinectl shell paging@ /bin/bash` and run stuff there), make sure you can hear stuff and no "ALSA lib ..." errors are printed (like above).
- In paging.conf, set "pjsua-device = ..." to match same output that you've tested earlier.
- While at it, make sure that "klaxon = ..." line points to existing and accessible (to that uid) file, if used.

I think that's it, hope it helps.

Cheers!

**Comment by mk-fg** [comment]
> Remove or disable JACK, forget it exists for the scope of this project, has nothing to do with it (unless, of course, you want to use it somehow).

To avoid confusion - given that pjsua auto-starts the thing if it can't use ALSA, and it's probably been installed as a dep of something, don't think you actually need to remove or disable it, just forget about it ;)

**Comment by mk-fg** [comment]
Also, if you've used something like "setup-scripts/paging-server-setup.orangepi.debian_jessie.sh" to install the thing on Raspberry Pi, that's what might've messed-up your ALSA config - these scripts are for Orange Pi only, as the name might suggest.

**Comment by fixyabrokestuff** [comment]
You are awesome!  Followed your suggestions and it works within five minutes.  Currently have it running on a fresh install of Ubuntu 16.04.

FYI, I didn't have a klaxon file configured.  If the parameter for klaxon in /etc/paging.conf is commented out you get the error message that you pointed to in the debug output.  The software will run but never answer.  Putting a path to a valid .wav file fixes the issue.

Most of my testing was done with script install.debian_jessie.sh.  The Bananna Pi script does a whole lot more in terms of getting the thing to startup automatically.  It was most useful in terms of understanding where things should go in an automated startup installation.

Thank you for all of the help and a really super piece of software.

**Comment by mk-fg** [comment]
> FYI, I didn't have a klaxon file configured. If the parameter for klaxon in /etc/paging.conf is commented out you get the error message that you pointed to in the debug output.

Hah, yeah, guess it just was never tested without that sound configured before.
Will fix it, thanks for pointing it out.
