### ISSUE TITLE
Should use Debian package for pjsua-python

### ISSUE THREAD

**Issue by ghost** [AccelerateNetworks/PagingServer#2]
There's a libpjsua-dev package in Python that should (but does not as of this writing) provide the necessary Python modules. The fact that it does not necessitates the extra hackery of d/l the source from pjproject, and is [Debian bug 768578](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768578). The bug is closed, the maintainer has uploaded a new version of the package that provides the python modules. I'm testing the new version now. It should be uploaded in a few weeks. In the meantime, if it works, I'll amend the installation instructions in my branch.

**Comment by ghost** [comment]
I've compiled the source package from the maintainer's QA page and verified that autoanswer.py works with the python-pjproject .deb it provides.

**Comment by danry25** [comment]
if its in Apt or Pip, I'd much rather pull pjsua from there! Then it'll actually get patches and maintenance from people more knowledgeable than thou. So, I should add [libpjproject-dev](https://packages.debian.org/jessie/libpjproject-dev) to the list of dependencies and drop the instructions to build PJSUA then?

**Comment by ghost** [comment]
No, because libpjproject-dev does not provide the Python modules. The source package provides the source tree from which to build the modules, but it's an old version and doesn't build correctly so it's not worth trifling with. The new package is [python-pjproject](https://packages.debian.org/sid/python-pjproject), which is OK to use in the deps list iff you're installing to Sid.The updated package is not in the testing yet. I expect it will be soon.

The [QA page](https://packages.qa.debian.org/p/pjproject.html) shows the progress of the package. It looks like it's already available in unstable, and hopefully will be in testing in 10 days or so. As it stands right now, we should be able to pull it using `apt-get install -t unstable python-pjproject` or plain `apt-get install python-pjproject` on any Sid box, though I don't recommend the former (easier and simpler IMO for me to provide the .debs and a script to install them in the correct order, which hopefully we won't need until the new packages are in the branch we normally use.) Or we could "upgrade" any autoanswering box to Sid if that's easier- but I counsel patience.

**Comment by mk-fg** [comment]
I'd also advise against ever pulling something from Sid into Jessie, esp. with deps.

As of cb3ef6f README has a description of how to build packages for both pjproject and python-pjproject with checkinstall on Jessie, as well as some other quirks of the whole process.

It should be easy to maybe host these debs in a thrid-party repository, if there's a need to install this stuff on many Jessie machines, otherwise - if it's just one-two boxes - can either be built there or debs just copied over and installed with `dpkg -i stuff.deb`.

In Sid (and the next stable whassit), it should be indeed possible to avoid all that and just use upstream packages.

**Comment by mk-fg** [comment]
And I think this one bites the dust.
